In [1]:
pip install pandas numpy scikit-learn matplotlib seaborn

Requirement already satisfied: pandas in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (2.3.3)
Requirement already satisfied: numpy in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (2.3.4)
Requirement already satisfied: scikit-learn in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (1.7.2)
Requirement already satisfied: matplotlib in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (3.10.7)
Requirement already satisfied: seaborn in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (0.13.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from pandas) (2025.2)
Requirement already satisfied: scipy>=1.8.0 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from scikit-learn) (1.5.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: contourpy>=1.0.1 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from matplotlib) (4.60.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from matplotlib) (25.0)
Requirement already satisfied: pillow>=8 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from matplotlib) (12.0.0)
Requirement already satisfied: pyparsing>=3 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from matplotlib) (3.2.5)
Requirement already satisfied: six>=1.5 in /Users/pintusingh/Desktop/fake-job-detection/venv/lib/python3.11/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 25.3 -> 26.0.1
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [4]:
import pandas as pd

data = pd.read_json('../data/News_Category_Dataset_v3.json', lines=True)
data.head()

,link,headline,category,short_description,authors,date
0,https://www.huffpost.com/entry/covid-boosters-...,Over 4 Million Americans Roll Up Sleeves For O...,U.S. NEWS,Health experts said it is too early to predict...,"Carla K. Johnson, AP",2022-09-23
1,https://www.huffpost.com/entry/american-airlin...,"American Airlines Flyer Charged, Banned For Li...",U.S. NEWS,He was subdued by passengers and crew when he ...,Mary Papenfuss,2022-09-23
2,https://www.huffpost.com/entry/funniest-tweets...,23 Of The Funniest Tweets About Cats And Dogs ...,COMEDY,"""Until you have a dog you don't understand wha...",Elyse Wanshel,2022-09-23
3,https://www.huffpost.com/entry/funniest-parent...,The Funniest Tweets From Parents This Week (Se...,PARENTING,"""Accidentally put grown-up toothpaste on my to...",Caroline Bologna,2022-09-23
4,https://www.huffpost.com/entry/amy-cooper-lose...,Woman Who Called Cops On Black Bird-Watcher Lo...,U.S. NEWS,Amy Cooper accused investment firm Franklin Te...,Nina Golgowski,2022-09-22

In [6]:
data.shape

(209527, 6)

In [7]:
data.isnull().sum()

link                 0
headline             0
category             0
short_description    0
authors              0
date                 0
dtype: int64

In [8]:
data['category'].value_counts()

category
POLITICS          35602
WELLNESS          17945
ENTERTAINMENT     17362
TRAVEL             9900
STYLE & BEAUTY     9814
PARENTING          8791
HEALTHY LIVING     6694
QUEER VOICES       6347
FOOD & DRINK       6340
BUSINESS           5992
COMEDY             5400
SPORTS             5077
BLACK VOICES       4583
HOME & LIVING      4320
PARENTS            3955
THE WORLDPOST      3664
WEDDINGS           3653
WOMEN              3572
CRIME              3562
IMPACT             3484
DIVORCE            3426
WORLD NEWS         3299
MEDIA              2944
WEIRD NEWS         2777
GREEN              2622
WORLDPOST          2579
RELIGION           2577
STYLE              2254
SCIENCE            2206
TECH               2104
TASTE              2096
MONEY              1756
ARTS               1509
ENVIRONMENT        1444
FIFTY              1401
GOOD NEWS          1398
U.S. NEWS          1377
ARTS & CULTURE     1339
COLLEGE            1144
LATINO VOICES      1130
CULTURE & ARTS     1074
EDUCATION          1014
Name: count, dtype: int64

In [9]:
data['date'] = pd.to_datetime(data['date'])
data.dtypes

link                         object
headline                     object
category                     object
short_description            object
authors                      object
date                 datetime64[ns]
dtype: object

In [10]:
data['full_text'] = data['headline'] + ' ' + data['short_description'].fillna('')
data['full_text'].head(3)

0    Over 4 Million Americans Roll Up Sleeves For O...
1    American Airlines Flyer Charged, Banned For Li...
2    23 Of The Funniest Tweets About Cats And Dogs ...
Name: full_text, dtype: object

In [11]:
data_sample = data.sample(n=10000, random_state=42).reset_index(drop=True)
data_sample.shape

(10000, 7)

In [15]:
#Clean function 
import re
import nltk
nltk.download('stopwords', quiet=True)
nltk.download('wordnet', quiet=True)
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = str(text).lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = [lemmatizer.lemmatize(w)
             for w in text.split()
             if w not in stop_words and len(w) > 2]
    return ' '.join(words)

In [13]:
data_sample['clean_text'] = data_sample['full_text'].apply(clean_text)
data_sample[['full_text', 'clean_text']].head(3)

,full_text,clean_text
0,What If We Were All Family Generation Changers...,family generation changer wont create new oppo...
1,Firestorm At AOL Over Employee Benefit Cuts It...,firestorm aol employee benefit cut glorious we...
2,Dakota Access Protesters Arrested As Deadline ...,dakota access protester arrested deadline pass...

In [14]:
import os
os.makedirs('../data', exist_ok=True)
data_sample.to_csv('../data/clean_data.csv', index=False)
data_sample.shape

(10000, 8)